#!/bin/bash

USERNAME="zany130"
ALGA_PATH="/home/${USERNAME}/.local/bin/alga"
TV_INPUT="HDMI_1"

case "$1/$2" in
    pre/*)
        logger -t lg-buddy-sleep "Pre-sleep: Checking TV state before $2"
        
        power_state=$(sudo -u "$USERNAME" "$ALGA_PATH" power screen-state 2>&1 | cut -d':' -f2 | xargs)
        
        logger -t lg-buddy-sleep "TV power state: $power_state"
        
        if [[ "$power_state" == "Active" ]]; then
            logger -t lg-buddy-sleep "Powering off TV"
            sudo -u "$USERNAME" "$ALGA_PATH" power off
        else
            logger -t lg-buddy-sleep "TV already off"
        fi
        ;;
        
    post/*)
        logger -t lg-buddy-sleep "Post-sleep: Woke up from $2"
        
        sleep 2
        
        power_state=$(sudo -u "$USERNAME" "$ALGA_PATH" power screen-state 2>&1 | cut -d':' -f2 | xargs)
        
        if [[ "$power_state" != "Active" ]]; then
            logger -t lg-buddy-sleep "Turning on TV and switching to $TV_INPUT"
            sudo -u "$USERNAME" "$ALGA_PATH" power on
            sleep 7
            sudo -u "$USERNAME" "$ALGA_PATH" input set "$TV_INPUT"
        else
            logger -t lg-buddy-sleep "TV already on, checking input"
            current_input=$(sudo -u "$USERNAME" "$ALGA_PATH" input get 2>&1 | grep -o 'HDMI_[0-9]\+')
            if [[ "$current_input" != "$TV_INPUT" ]]; then
                logger -t lg-buddy-sleep "Switching to $TV_INPUT"
                sudo -u "$USERNAME" "$ALGA_PATH" input set "$TV_INPUT"
            fi
        fi
        ;;
esac

exit 0
