#!/bin/bash

#Script goes in /etc/NetworkManager/dispatcher.d/pre-down.d/
#This was not my first choice but other options I tried would not work:
# a.) systemd service that runs before shutdown - The system would go to sleep somewhere in the middle of the script.
# b.) Place in /lib/systemd/system-sleep/ - Putting an applicable 'Pre' script in here did run, but the network would already be down, thus the script would fail.

#We only want this to run when the network is going down due to sleep/suspend
#This might need to be more fleshed out ot handle different types such as hibernate

# UPDATE THESE: Change to match your setup
USERNAME="zany130"
ALGA_PATH="/home/${USERNAME}/.local/bin/alga"

if journalctl -u NetworkManager | tail -1 | grep -q "reason 'sleeping'"
then
    power_state=$($ALGA_PATH power screen-state | cut -d':' -f2 | xargs)

    if [[ "$power_state" == "Active" ]]
    then
        $ALGA_PATH power off
    else
        echo "TV is powered off already."
    fi
fi

exit 0
